version: 2.1

jobs:
  build:
    docker:
      - image: elucidataincrohit/frontendv2:2.2

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Build application
          command: npm run build

  deploy:
    docker:
      - image: circleci/node:14

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      - run:
          name: Deploy to S3
          command: |
            aws s3 sync ./dist/ s3://sidebarbucket/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
